/**
 * Video package query helpers.
 *
 * Video packages are complete, platform-ready video briefs generated by the
 * Content Strike Team operator. Each package contains a hook (with A/B
 * variants), an ordered scene list, a thumbnail concept, optional caption,
 * and a call-to-action.
 */

import 'server-only'

import type { SupabaseClient } from '@supabase/supabase-js'
import type { Database } from '../types'

type TypedClient = SupabaseClient<Database>

// ---------------------------------------------------------------------------
// Inline types (video_packages table not yet in generated Database type)
// ---------------------------------------------------------------------------

export type VideoPackagePlatform =
  | 'x'
  | 'linkedin'
  | 'instagram'
  | 'tiktok'
  | 'youtube'
  | 'email'
  | 'universal'

export type VideoPackageStatus =
  | 'draft'
  | 'review'
  | 'approved'
  | 'published'
  | 'archived'
  | 'rejected'

export interface VideoPackageHook {
  primary: string
  variants: string[]
}

export interface VideoPackageScene {
  order: number
  title: string
  script: string
  visual_direction: string
  duration_seconds: number
}

export interface VideoPackageThumbnailConcept {
  headline: string
  visual_description: string
  color_scheme: string
  text_overlay: string
}

export interface VideoPackageCta {
  text: string
  type: string
  destination?: string
}

export interface VideoPackage {
  id: string
  workspace_id: string
  mission_id: string | null
  asset_id: string | null
  title: string
  platform: VideoPackagePlatform
  hook: VideoPackageHook
  scenes: VideoPackageScene[]
  thumbnail_concept: VideoPackageThumbnailConcept
  caption: string | null
  cta: VideoPackageCta | null
  status: VideoPackageStatus
  confidence_score: number | null
  metadata: Record<string, unknown>
  created_at: string
  updated_at: string
}

export interface VideoPackageInsert {
  workspace_id: string
  mission_id?: string | null
  asset_id?: string | null
  title: string
  platform: VideoPackagePlatform
  hook: VideoPackageHook
  scenes: VideoPackageScene[]
  thumbnail_concept: VideoPackageThumbnailConcept
  caption?: string | null
  cta?: VideoPackageCta | null
  status?: VideoPackageStatus
  confidence_score?: number | null
  metadata?: Record<string, unknown>
}

export type VideoPackageUpdate = Partial<Omit<VideoPackageInsert, 'workspace_id'>>

// ---------------------------------------------------------------------------
// Filter / pagination helpers
// ---------------------------------------------------------------------------

export interface VideoPackageFilters {
  platform?: VideoPackagePlatform
  status?: VideoPackageStatus
  search?: string
}

export interface VideoPackagePagination {
  page?: number
  pageSize?: number
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

/**
 * Returns a paginated list of video packages for a workspace.
 * Supports optional platform/status filters and title full-text search.
 */
export async function getVideoPackages(
  client: TypedClient,
  workspaceId: string,
  filters: VideoPackageFilters = {},
  pagination: VideoPackagePagination = {},
): Promise<{ data: VideoPackage[] | null; error: string | null; total: number }> {
  const page = Math.max(1, pagination.page ?? 1)
  const pageSize = Math.min(100, Math.max(1, pagination.pageSize ?? 20))
  const offset = (page - 1) * pageSize

  let query = client
    .from('video_packages')
    .select('*', { count: 'exact' })
    .eq('workspace_id', workspaceId)
    .order('created_at', { ascending: false })
    .range(offset, offset + pageSize - 1)

  if (filters.platform) {
    query = query.eq('platform', filters.platform)
  }

  if (filters.status) {
    query = query.eq('status', filters.status)
  }

  if (filters.search) {
    query = query.ilike('title', `%${filters.search}%`)
  }

  const { data, error, count } = await query

  if (error) {
    return { data: null, error: error.message, total: 0 }
  }

  return {
    data: (data ?? []) as unknown as VideoPackage[],
    error: null,
    total: count ?? 0,
  }
}

/**
 * Returns a single video package by ID scoped to the workspace.
 */
export async function getVideoPackage(
  client: TypedClient,
  id: string,
  workspaceId: string,
): Promise<{ data: VideoPackage | null; error: string | null }> {
  const { data, error } = await client
    .from('video_packages')
    .select('*')
    .eq('id', id)
    .eq('workspace_id', workspaceId)
    .single()

  if (error) {
    return { data: null, error: error.message }
  }

  return { data: data as unknown as VideoPackage | null, error: null }
}

/**
 * Inserts a new video package.
 */
export async function createVideoPackage(
  client: TypedClient,
  data: VideoPackageInsert,
): Promise<{ data: VideoPackage | null; error: string | null }> {
  const { data: created, error } = await client
    .from('video_packages')
    .insert(data as unknown as Database['public']['Tables']['video_packages']['Insert'])
    .select()
    .single()

  if (error) {
    return { data: null, error: error.message }
  }

  return { data: created as unknown as VideoPackage | null, error: null }
}

/**
 * Updates fields on an existing video package.
 * Scoped to workspaceId for safety.
 */
export async function updateVideoPackage(
  client: TypedClient,
  id: string,
  workspaceId: string,
  updates: Partial<VideoPackageUpdate>,
): Promise<{ data: VideoPackage | null; error: string | null }> {
  const { data, error } = await client
    .from('video_packages')
    .update(updates as unknown as Database['public']['Tables']['video_packages']['Update'])
    .eq('id', id)
    .eq('workspace_id', workspaceId)
    .select()
    .single()

  if (error) {
    return { data: null, error: error.message }
  }

  return { data: data as unknown as VideoPackage | null, error: null }
}

/**
 * Hard-deletes a video package.
 * Scoped to workspaceId for safety.
 */
export async function deleteVideoPackage(
  client: TypedClient,
  id: string,
  workspaceId: string,
): Promise<{ error: string | null }> {
  const { error } = await client
    .from('video_packages')
    .delete()
    .eq('id', id)
    .eq('workspace_id', workspaceId)

  if (error) {
    return { error: error.message }
  }

  return { error: null }
}

/**
 * Returns all video packages linked to a specific mission.
 * Ordered by created_at ascending to show generation sequence.
 */
export async function getVideoPackagesByMission(
  client: TypedClient,
  missionId: string,
  workspaceId: string,
): Promise<{ data: VideoPackage[] | null; error: string | null }> {
  const { data, error } = await client
    .from('video_packages')
    .select('*')
    .eq('workspace_id', workspaceId)
    .eq('mission_id', missionId)
    .order('created_at', { ascending: true })

  if (error) {
    return { data: null, error: error.message }
  }

  return { data: (data ?? []) as unknown as VideoPackage[], error: null }
}
