/**
 * /start <link_code> — Account linking handler.
 *
 * The link_code is an HMAC-signed token generated by the dashboard Settings page.
 * Format: base64(userId:workspaceId:timestamp):hmacSignature
 */

import crypto from 'crypto'
import { getTelegramConfig } from '../config'
import { linkTelegramAccount } from '@/lib/supabase/queries/telegram'
import { formatWelcome, formatError } from '../formatter'
import type { TelegramHandlerContext } from '../types'

const LINK_CODE_MAX_AGE_MS = 15 * 60 * 1000 // 15 minutes

interface ParsedCode {
  userId: string
  workspaceId: string
  timestamp: number
}

function parseAndVerifyCode(code: string): ParsedCode | null {
  try {
    const separatorIdx = code.lastIndexOf(':')
    if (separatorIdx <= 0) return null

    const payload = code.slice(0, separatorIdx)
    const signature = code.slice(separatorIdx + 1)
    if (!payload || !signature) return null

    const { linkSecret } = getTelegramConfig()

    const expectedSig = crypto
      .createHmac('sha256', linkSecret)
      .update(payload)
      .digest('hex')

    // Both must be valid hex of equal length for timingSafeEqual
    const sigBuf = Buffer.from(signature, 'hex')
    const expectedBuf = Buffer.from(expectedSig, 'hex')
    if (sigBuf.length !== expectedBuf.length || !crypto.timingSafeEqual(sigBuf, expectedBuf)) {
      return null
    }

    const decoded = Buffer.from(payload, 'base64').toString('utf-8')
    const decodedParts = decoded.split(':')
    const [userId, workspaceId, timestampStr] = decodedParts
    const timestamp = Number(timestampStr)

    if (!userId || !workspaceId || isNaN(timestamp)) return null
    if (Date.now() - timestamp > LINK_CODE_MAX_AGE_MS) return null

    return { userId, workspaceId, timestamp }
  } catch {
    return null
  }
}

export async function handleStart(ctx: TelegramHandlerContext): Promise<string> {
  const code = ctx.args?.trim()

  if (!code) {
    return formatError('Usage: /start <link_code> — Get your link code from the Agent MOE dashboard Settings page.')
  }

  const parsed = parseAndVerifyCode(code)
  if (!parsed) {
    return formatError('Invalid or expired link code. Generate a new one from Settings.')
  }

  const { data, error } = await linkTelegramAccount(ctx.db, {
    user_id: parsed.userId,
    workspace_id: parsed.workspaceId,
    chat_id: ctx.chatId,
    username: ctx.username,
  })

  if (error) {
    console.error('[Telegram] /start linking failed:', error)
    return formatError('Failed to link account. Try again or contact support.')
  }

  if (!data) {
    return formatError('Unexpected error during linking.')
  }

  // Upsert a connector record so the Connectors page shows Telegram as connected
  await ctx.db
    .from('connectors')
    .upsert(
      {
        workspace_id: parsed.workspaceId,
        platform: 'telegram' as const,
        name: 'Telegram',
        status: 'connected' as const,
        config: { chat_id: ctx.chatId, username: ctx.username ?? '' },
        credentials: {},
      },
      { onConflict: 'workspace_id,platform' }
    )
    .then(({ error: upsertErr }) => {
      if (upsertErr) console.error('[Telegram] connector upsert failed:', upsertErr)
    })

  return formatWelcome(ctx.username)
}
