/**
 * Revenue Lab — domain types.
 *
 * These types describe the data structures used by the Revenue Lab feature:
 * CTA generation, pricing ladder visualisation, funnel rules, and conversion
 * path planning. They are intentionally decoupled from the Supabase schema so
 * the feature layer can evolve independently of the DB shape.
 */

// ---------------------------------------------------------------------------
// CTA Variants
// ---------------------------------------------------------------------------

/**
 * A single CTA variant generated by the Revenue Closer AI for a specific
 * platform and content type combination.
 */
export interface CTAVariant {
  id: string
  offer_id: string
  /** Platform the CTA is written for, e.g. 'x' | 'linkedin' | 'instagram' | 'youtube' | 'email' | 'general' */
  platform: string
  /** Content format, e.g. 'post' | 'thread' | 'video_script' | 'email' | 'caption' */
  content_type: string
  headline: string
  body: string
  button_text: string
  urgency_level: 'low' | 'medium' | 'high'
  /** Tone of voice, e.g. 'conversational' | 'authoritative' | 'urgent' | 'educational' */
  tone: string
  /** AI confidence score 0–100 */
  confidence: number
  generated_at: string
}

// ---------------------------------------------------------------------------
// Pricing Ladder
// ---------------------------------------------------------------------------

/**
 * A single tier in the pricing ladder, computed from an OfferRow.
 */
export interface PricingLadderTier {
  offer_id: string
  name: string
  offer_type: string
  price_cents: number | null
  /** Human-readable price string, e.g. '$0', '$97', '$2,997' */
  price_display: string
  cta_text: string
  cta_url: string
  status: string
  /** Computed tier label based on price: 'Free' | 'Entry' | 'Mid' | 'Premium' | 'Elite' */
  tier_label: string
  description: string
}

// ---------------------------------------------------------------------------
// Funnel Rules
// ---------------------------------------------------------------------------

/**
 * A rule that controls which offer or CTA the system selects when generating
 * content. Rules are evaluated in priority order (lower number = higher priority).
 */
export interface FunnelRule {
  id: string
  /** Human-readable condition expression, e.g. 'content_type === post AND platform === linkedin' */
  condition: string
  action: 'use_offer' | 'use_cta' | 'skip_cta'
  offer_id?: string
  cta_text?: string
  /** Lower number = higher priority */
  priority: number
  notes?: string
}

// ---------------------------------------------------------------------------
// Conversion Paths
// ---------------------------------------------------------------------------

/**
 * A single step in a conversion path sequence.
 */
export interface ConversionPathStep {
  step_number: number
  offer_id: string
  /** When to trigger this step: 'immediate' | 'after_7_days' | 'on_purchase' | 'manual' */
  trigger: string
  cta_text?: string
}

/**
 * An ordered sequence of offers that guide a prospect from entry to purchase.
 */
export interface ConversionPath {
  id: string
  name: string
  /** The lead magnet or free entry point for this path */
  entry_offer_id: string
  steps: ConversionPathStep[]
}

// ---------------------------------------------------------------------------
// Revenue Stats
// ---------------------------------------------------------------------------

/**
 * Aggregate revenue stats computed from the offers in a workspace.
 */
export interface RevenueStats {
  total_offers: number
  active_offers: number
  lead_magnets: number
  paid_offers: number
  highest_ticket_cents: number | null
  /** Human-readable price range, e.g. 'Free → $2,997' */
  price_range_display: string
  by_type: Record<string, number>
}

// ---------------------------------------------------------------------------
// CTA Generation I/O
// ---------------------------------------------------------------------------

/**
 * Input for the CTAEngine.generateCTAs method.
 */
export interface GenerateCTAsInput {
  offer_id: string
  workspace_id: string
  /** List of platform strings to generate CTAs for */
  platforms: string[]
  /** List of content type strings to generate CTAs for */
  content_types: string[]
  /** Number of variants per platform×content_type combination. Defaults to 2. */
  count_per_combination?: number
}

/**
 * Result returned by CTAEngine.generateCTAs.
 */
export interface GenerateCTAsResult {
  offer_id: string
  variants: CTAVariant[]
  generated_at: string
}
