-- =============================================================================
-- Migration 00004: Create missions table
-- =============================================================================
-- Purpose: Top-level instructions from the user. A mission is a natural language
--          command ("Launch a thread campaign around my new offer") that the
--          Mission Engine decomposes into jobs for operator teams.
-- =============================================================================

-- =============================================================================
-- ENUMS
-- =============================================================================

CREATE TYPE public.mission_status AS ENUM (
    'pending',    -- Created, not yet processed by Mission Engine
    'planning',   -- Mission Engine is decomposing into jobs
    'running',    -- Jobs are actively executing
    'paused',     -- User manually paused execution
    'completed',  -- All jobs completed successfully
    'failed'      -- One or more critical jobs failed; mission halted
);

CREATE TYPE public.mission_priority AS ENUM (
    'low',     -- Background task, no urgency
    'normal',  -- Standard execution priority
    'high',    -- Elevated priority, processes before normal queue
    'urgent'   -- Immediate execution, interrupts current queue
);

COMMENT ON TYPE public.mission_status IS 'Lifecycle state of a mission from creation to completion or failure.';
COMMENT ON TYPE public.mission_priority IS 'Execution priority of a mission in the job queue.';

-- =============================================================================
-- TABLE: missions
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.missions (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    user_id       UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,

    -- Human-readable mission title (auto-generated from instruction if not provided)
    title         TEXT NOT NULL,

    -- The raw natural language instruction from the user
    instruction   TEXT NOT NULL,

    -- Current lifecycle state
    status        public.mission_status NOT NULL DEFAULT 'pending',

    -- Execution priority in queue
    priority      public.mission_priority NOT NULL DEFAULT 'normal',

    -- Structured plan produced by Mission Engine (JSON job tree with dependencies)
    -- Schema: { summary, estimated_jobs, jobs: [{ id, type, operator_team, ... }] }
    plan_json     JSONB NOT NULL DEFAULT '{}',

    -- Arbitrary metadata: context_urls, tags, campaign links, etc.
    meta          JSONB NOT NULL DEFAULT '{}',

    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  public.missions IS 'Top-level user instructions. Mission Engine decomposes these into jobs for operator teams.';
COMMENT ON COLUMN public.missions.workspace_id IS 'FK to workspaces. Workspace that owns this mission.';
COMMENT ON COLUMN public.missions.user_id IS 'FK to users. User who created this mission.';
COMMENT ON COLUMN public.missions.title IS 'Short human-readable title. Auto-generated by Mission Engine if not provided by user.';
COMMENT ON COLUMN public.missions.instruction IS 'The raw natural language mission text entered by the user.';
COMMENT ON COLUMN public.missions.status IS 'Current lifecycle state. Updated by Mission Engine and job execution pipeline.';
COMMENT ON COLUMN public.missions.priority IS 'Queue priority. Urgent missions interrupt the current job queue.';
COMMENT ON COLUMN public.missions.plan_json IS 'Structured decomposition plan produced by Mission Engine. Contains job tree with types, operators, and dependencies.';
COMMENT ON COLUMN public.missions.meta IS 'Arbitrary metadata: context URLs, related campaigns, operator notes, tags.';

-- =============================================================================
-- CONSTRAINTS
-- =============================================================================

ALTER TABLE public.missions
    ADD CONSTRAINT missions_title_not_empty CHECK (length(trim(title)) > 0);

ALTER TABLE public.missions
    ADD CONSTRAINT missions_instruction_not_empty CHECK (length(trim(instruction)) > 0);

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================

ALTER TABLE public.missions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "missions_select_owner"
    ON public.missions
    FOR SELECT
    USING (
        workspace_id IN (
            SELECT id FROM public.workspaces WHERE user_id = auth.uid()
        )
    );

CREATE POLICY "missions_insert_owner"
    ON public.missions
    FOR INSERT
    WITH CHECK (
        workspace_id IN (
            SELECT id FROM public.workspaces WHERE user_id = auth.uid()
        )
    );

CREATE POLICY "missions_update_owner"
    ON public.missions
    FOR UPDATE
    USING (
        workspace_id IN (
            SELECT id FROM public.workspaces WHERE user_id = auth.uid()
        )
    )
    WITH CHECK (
        workspace_id IN (
            SELECT id FROM public.workspaces WHERE user_id = auth.uid()
        )
    );

CREATE POLICY "missions_delete_owner"
    ON public.missions
    FOR DELETE
    USING (
        workspace_id IN (
            SELECT id FROM public.workspaces WHERE user_id = auth.uid()
        )
    );

-- =============================================================================
-- INDEXES
-- =============================================================================

-- Composite index for dashboard queries: all missions for workspace, newest first
CREATE INDEX IF NOT EXISTS idx_missions_workspace_created
    ON public.missions (workspace_id, created_at DESC);

-- Filter by status (common in active mission views)
CREATE INDEX IF NOT EXISTS idx_missions_status
    ON public.missions (status);

-- Filter by workspace + status (most common dashboard query)
CREATE INDEX IF NOT EXISTS idx_missions_workspace_status
    ON public.missions (workspace_id, status);

-- Priority queue ordering
CREATE INDEX IF NOT EXISTS idx_missions_priority_created
    ON public.missions (priority DESC, created_at ASC)
    WHERE status = 'pending';

-- User-scoped lookup
CREATE INDEX IF NOT EXISTS idx_missions_user_id
    ON public.missions (user_id);
